dist: trusty

sudo: required

notifications:
  email: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
 global:
  - SWIG=swig3.0
 matrix:
  - CC=gcc-5 PYSAM_VERSION='pysam==0.9.0'
  - CC=gcc PYSAM_VERSION='pysam==0.9.0'
  - CC=gcc-5 PYSAM_VERSION='pysam==0.10.0'
  - CC=gcc PYSAM_VERSION='pysam==0.10.0'
  - CC=gcc-5 PYSAM_VERSION='pysam'
  - CC=gcc PYSAM_VERSION='pysam'
  include:
    services:
      - docker
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      - CC=gcc

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - gcc-5
     - g++-5

before_install:
  - sudo add-apt-repository ppa:nschloe/swig-backports -y
  - sudo apt-get -qq update
  - sudo apt-get install -y swig3.0

install:
  # setuptools < 18.0 has issues with Cython as a dependency
  - pip install Cython
  - [ $PYSAM_VERSION] && sed -i "s/pysam>=0.9.0,<=0.11.1/$PYSAM_VERSION/" setup.py
  # old setuptools also has a bug for extras, but it still compiles
  - pip install '.[htseq-qa]'
 
script:
  - python .travis_test.py
  # try and make wheels
  - [ $DOCKER_IMAGE ] && docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/buildwheels.sh
  - [ $DOCKER_IMAGE ] && ls wheelhouse/
