services:
  - docker

notifications:
  email: false

language: python

env:
 global:
  - SWIG=swig3.0

matrix:
  include:
   - env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
     python: 3.6
     os: linux
     dist: trusty
     sudo: required
   - env: CC=gcc PYSAM_VERSION='pysam'
     python: 2.7
     os: linux
     dist: trusty
     sudo: required
   - env: CC=gcc PYSAM_VERSION='pysam'
     python: 3.5
     os: linux
     dist: trusty
     sudo: required
   - env: CC=gcc PYSAM_VERSION='pysam'
     python: 3.6
     os: linux
     dist: trusty
     sudo: required
   - env: CC=gcc PYSAM_VERSION='pysam'
     python: 3.7
     os: linux
     dist: bionic
     sudo: required
   - env: CC=gcc PYSAM_VERSION='pysam'
     python: 3.8
     os: linux
     dist: bionic
     sudo: required
   - env: CC=gcc PYSAM_VERSION='pysam>=0.13.0' CONDA_PY='2.7'
     language: generic
     os: osx
   - env: CC=gcc PYSAM_VERSION='pysam>=0.13.0' CONDA_PY='3.6'
     language: generic
     os: osx
   - env: CC=gcc PYSAM_VERSION='pysam>=0.13.0' CONDA_PY='3.7'
     language: generic
     os: osx
   - env: CC=gcc PYSAM_VERSION='pysam>=0.13.0' CONDA_PY='3.8'
     language: generic
     os: osx
   - env: CC=gcc PYSAM_VERSION='pysam>=0.13.0' CONDA_PY='2.7'
     language: generic
     os: osx
     osx_image: xcode11
   - env: CC=gcc PYSAM_VERSION='pysam>=0.13.0' CONDA_PY='3.6'
     language: generic
     os: osx
     osx_image: xcode11
   - env: CC=gcc PYSAM_VERSION='pysam>=0.13.0' CONDA_PY='3.7'
     language: generic
     os: osx
     osx_image: xcode11
   - env: CC=gcc PYSAM_VERSION='pysam>=0.13.0' CONDA_PY='3.8'
     language: generic
     os: osx
     osx_image: xcode11

before_install:
  - ./.travis_before_install.sh

install:
  - ./.travis_install.sh
 
script:
  - ./.travis_test.sh

after_success:
  - ./.travis_deploy.sh
